export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'RESOURCE_NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'COMPILE_ERROR'
  | 'COMPILE_TIMEOUT'
  | 'COMPILE_QUEUE_FULL'
  | 'INTERNAL_ERROR';

