/**
 * arduino-generator.ts
 *
 * A Blockly CodeGenerator that emits valid Arduino C++ (a subset of C++11).
 * Handles both custom Arduino blocks and the standard Blockly library blocks
 * exposed in the toolbox (logic, loops, math, variables, procedures).
 *
 * Usage:
 *   import { arduinoGenerator } from './arduino-generator';
 *   const code = arduinoGenerator.workspaceToCode(workspace);
 */
import { CodeGenerator, Names } from 'blockly/core';
import type { Block, Workspace } from 'blockly/core';

// ─── Operator precedence for C++ ─────────────────────────────────────────────
export enum Order {
  ATOMIC = 0, // Literals, identifiers, function calls
  UNARY = 3, // ! ~ - + (prefix)
  MULTIPLY = 5, // * / %
  ADD = 6, // + -
  RELATIONAL = 9, // < <= > >=
  EQUALITY = 10, // == !=
  LOGICAL_AND = 14, // &&
  LOGICAL_OR = 15, // ||
  ASSIGNMENT = 17, // = += -= etc.
  NONE = 99, // No parentheses needed
}

// ─────────────────────────────────────────────────────────────────────────────
// Generator instance
// ─────────────────────────────────────────────────────────────────────────────
export const arduinoGenerator = new CodeGenerator('Arduino');
arduinoGenerator.INDENT = '  ';

const RESERVED_WORDS =
  'alignas,alignof,and,and_eq,asm,auto,bitand,bitor,bool,break,case,catch,char,char8_t,char16_t,char32_t,class,compl,concept,const,consteval,constexpr,constinit,const_cast,continue,co_await,co_return,co_yield,decltype,default,delete,do,double,dynamic_cast,else,enum,explicit,export,extern,false,float,for,friend,goto,if,inline,int,long,mutable,namespace,new,noexcept,not,not_eq,nullptr,operator,or,or_eq,private,protected,public,register,reinterpret_cast,requires,return,short,signed,sizeof,static,static_assert,static_cast,struct,switch,template,this,thread_local,throw,true,try,typedef,typeid,typename,union,unsigned,using,virtual,void,volatile,wchar_t,while,xor,xor_eq,' +
  'setup,loop,pinMode,digitalWrite,digitalRead,analogRead,analogWrite,delay,delayMicroseconds,millis,micros,Serial,HIGH,LOW,INPUT,OUTPUT,INPUT_PULLUP,LED_BUILTIN';

arduinoGenerator.addReservedWords(RESERVED_WORDS);

(arduinoGenerator as any).init = function (workspace: Workspace) {
  this.definitions_ = Object.create(null);
  this.functionNames_ = Object.create(null);

  if (!this.nameDB_) {
    this.nameDB_ = new Names(this.RESERVED_WORDS_ || '');
  } else {
    this.nameDB_.reset();
  }

  this.nameDB_.setVariableMap(workspace.getVariableMap());
  this.nameDB_.populateVariables(workspace);
  this.nameDB_.populateProcedures(workspace);
};

/**
 * Called after all blocks are processed. Prepends global variable declarations
 * collected during generation, then wraps with the Arduino boilerplate header.
 */
(arduinoGenerator as any).finish = function (code: string): string {
  // Collect variable declarations stored by variables_set blocks
  const varDecls = Object.values(this.definitions_).join('\n');
  const header = '// Generated by Tinkergyan Block Editor\n#include <Arduino.h>\n';
  return [header, varDecls ? varDecls + '\n' : '', code].filter(Boolean).join('\n');
};

/** Handle statement blocks that generate naked values (e.g. millis() as statement). */
(arduinoGenerator as any).scrubNakedValue = function (line: string): string {
  return `${line};\n`;
};

/**
 * Concatenate this block's code with the next connected statement block.
 * Mirrors the pattern used in Blockly's built-in generators.
 */
(arduinoGenerator as any).scrub_ = function (block: Block, code: string, thisOnly = false): string {
  const next = block.nextConnection?.targetBlock();
  const nextCode = !thisOnly && next ? (this as CodeGenerator).blockToCode(next) : '';
  return code + (Array.isArray(nextCode) ? nextCode[0] : nextCode);
};

// ─────────────────────────────────────────────────────────────────────────────
// ARDUINO STRUCTURE BLOCKS
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['arduino_program'] = function (block, generator) {
  const setup = generator.statementToCode(block, 'SETUP');
  const loop = generator.statementToCode(block, 'LOOP');

  return [
    'void setup() {',
    setup || `${generator.INDENT}// empty`,
    '}',
    '',
    'void loop() {',
    loop || `${generator.INDENT}// empty`,
    '}',
    '',
  ].join('\n');
};

// ─────────────────────────────────────────────────────────────────────────────
// DIGITAL I/O
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['arduino_pin_mode'] = function (block) {
  const pin = block.getFieldValue('PIN') as string;
  const mode = block.getFieldValue('MODE') as string;
  return `pinMode(${pin}, ${mode});\n`;
};

arduinoGenerator.forBlock['arduino_digital_write'] = function (block) {
  const pin = block.getFieldValue('PIN') as string;
  const value = block.getFieldValue('VALUE') as string;
  return `digitalWrite(${pin}, ${value});\n`;
};

arduinoGenerator.forBlock['arduino_digital_read'] = function (block) {
  const pin = block.getFieldValue('PIN') as string;
  return [`digitalRead(${pin})`, Order.ATOMIC] as [string, Order];
};

// ─────────────────────────────────────────────────────────────────────────────
// ANALOG I/O
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['arduino_analog_read'] = function (block) {
  const pin = block.getFieldValue('PIN') as string;
  return [`analogRead(${pin})`, Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['arduino_analog_write'] = function (block, generator) {
  const pin = block.getFieldValue('PIN') as string;
  const value = generator.valueToCode(block, 'VALUE', Order.NONE) || '0';
  return `analogWrite(${pin}, ${value});\n`;
};

// ─────────────────────────────────────────────────────────────────────────────
// CONTROL / TIMING
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['arduino_delay'] = function (block, generator) {
  const time = generator.valueToCode(block, 'DELAY_TIME', Order.ATOMIC) || '0';
  const unit = block.getFieldValue('TIME_UNIT');
  if (unit === 'sec') {
    return `delay(${time} * 1000UL);\n`;
  } else if (unit === 'micro') {
    return `delayMicroseconds(${time});\n`;
  }
  return `delay(${time});\n`;
};

arduinoGenerator.forBlock['arduino_millis'] = function () {
  return ['millis()', Order.ATOMIC] as [string, Order];
};

// ─────────────────────────────────────────────────────────────────────────────
// SERIAL
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['arduino_serial_begin'] = function (block) {
  const baud = block.getFieldValue('BAUD') as string;
  return `Serial.begin(${baud});\n`;
};

arduinoGenerator.forBlock['arduino_serial_print'] = function (block, generator) {
  const value = generator.valueToCode(block, 'VALUE', Order.NONE) || '""';
  return `Serial.print(${value});\n`;
};

arduinoGenerator.forBlock['arduino_serial_println'] = function (block, generator) {
  const value = generator.valueToCode(block, 'VALUE', Order.NONE) || '""';
  return `Serial.println(${value});\n`;
};

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD BLOCKLY — LOGIC
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['controls_if'] = function (block, generator) {
  let code = '';
  let n = 0;
  do {
    const condition = generator.valueToCode(block, `IF${n}`, Order.NONE) || 'false';
    const branch = generator.statementToCode(block, `DO${n}`);
    code += `${n > 0 ? ' else ' : ''}if (${condition}) {\n${branch}}`;
    n++;
  } while (block.getInput(`IF${n}`));

  if (block.getInput('ELSE')) {
    const branch = generator.statementToCode(block, 'ELSE');
    code += ` else {\n${branch}}`;
  }
  return `${code}\n`;
};

arduinoGenerator.forBlock['logic_compare'] = function (block, generator) {
  const OPS: Record<string, string> = {
    EQ: '==',
    NEQ: '!=',
    LT: '<',
    LTE: '<=',
    GT: '>',
    GTE: '>=',
  };
  const op = OPS[block.getFieldValue('OP') as string];
  const lhs = generator.valueToCode(block, 'A', Order.RELATIONAL) || '0';
  const rhs = generator.valueToCode(block, 'B', Order.RELATIONAL) || '0';
  return [`${lhs} ${op} ${rhs}`, Order.EQUALITY] as [string, Order];
};

arduinoGenerator.forBlock['logic_operation'] = function (block, generator) {
  const isAnd = block.getFieldValue('OP') === 'AND';
  const op = isAnd ? '&&' : '||';
  const order = isAnd ? Order.LOGICAL_AND : Order.LOGICAL_OR;
  const lhs = generator.valueToCode(block, 'A', order) || 'false';
  const rhs = generator.valueToCode(block, 'B', order) || 'false';
  return [`${lhs} ${op} ${rhs}`, order] as [string, Order];
};

arduinoGenerator.forBlock['logic_negate'] = function (block, generator) {
  const val = generator.valueToCode(block, 'BOOL', Order.UNARY) || 'false';
  return [`!${val}`, Order.UNARY] as [string, Order];
};

arduinoGenerator.forBlock['logic_boolean'] = function (block) {
  return [block.getFieldValue('BOOL') === 'TRUE' ? 'true' : 'false', Order.ATOMIC] as [
    string,
    Order,
  ];
};

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD BLOCKLY — LOOPS
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['controls_repeat_ext'] = function (block, generator) {
  const count = generator.valueToCode(block, 'TIMES', Order.NONE) || '0';
  const branch = generator.statementToCode(block, 'DO');
  return `for (int _i = 0; _i < ${count}; _i++) {\n${branch}}\n`;
};

arduinoGenerator.forBlock['controls_whileUntil'] = function (block, generator) {
  const isUntil = block.getFieldValue('MODE') === 'UNTIL';
  const condition = generator.valueToCode(block, 'BOOL', Order.NONE) || 'false';
  const branch = generator.statementToCode(block, 'DO');
  const cond = isUntil ? `!(${condition})` : condition;
  return `while (${cond}) {\n${branch}}\n`;
};

arduinoGenerator.forBlock['controls_for'] = function (block, generator) {
  const varName = generator.getVariableName(block.getFieldValue('VAR'));
  const from = generator.valueToCode(block, 'FROM', Order.NONE) || '0';
  const to = generator.valueToCode(block, 'TO', Order.NONE) || '0';
  const by = generator.valueToCode(block, 'BY', Order.NONE) || '1';
  const branch = generator.statementToCode(block, 'DO');

  // Determine loop direction at code-gen time if literals are known
  const fromNum = parseFloat(from);
  const toNum = parseFloat(to);
  const byNum = parseFloat(by);
  const ascending = isNaN(fromNum) || isNaN(toNum) || isNaN(byNum) || fromNum <= toNum;
  const cmp = ascending ? '<=' : '>=';

  return `for (int ${varName} = ${from}; ${varName} ${cmp} ${to}; ${varName} += ${by}) {\n${branch}}\n`;
};

arduinoGenerator.forBlock['controls_flow_statements'] = function (block) {
  return block.getFieldValue('FLOW') === 'BREAK' ? 'break;\n' : 'continue;\n';
};

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD BLOCKLY — TEXT
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['text'] = function (block) {
  const textValue = block.getFieldValue('TEXT') as string;
  // Escape strings properly for C++
  const escaped = textValue.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return [`String("${escaped}")`, Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['text_join'] = function (block, generator) {
  const itemCount = (block as any).itemCount_;
  if (itemCount === 0) return ['""', Order.ATOMIC] as [string, Order];
  if (itemCount === 1) {
    const element = generator.valueToCode(block, 'ADD0', Order.NONE) || '""';
    return [`String(${element})`, Order.ATOMIC] as [string, Order];
  }
  let code = `String(${generator.valueToCode(block, 'ADD0', Order.NONE) || '""'})`;
  for (let i = 1; i < itemCount; i++) {
    const element = generator.valueToCode(block, `ADD${i}`, Order.NONE) || '""';
    code += ` + String(${element})`;
  }
  return [code, Order.ADD] as [string, Order];
};

arduinoGenerator.forBlock['text_append'] = function (block, generator) {
  const varName = generator.getVariableName(block.getFieldValue('VAR'));
  const value = generator.valueToCode(block, 'TEXT', Order.NONE) || '""';

  // Need to declare it as String instead of int if it's text,
  // but for now we fallback to int, so append is tricky.
  // We'll declare it as String to allow appending
  (generator as any).definitions_[`var_${varName}`] = `String ${varName} = "";`;

  return `${varName} += String(${value});\n`;
};

arduinoGenerator.forBlock['text_length'] = function (block, generator) {
  const text = generator.valueToCode(block, 'VALUE', Order.NONE) || '""';
  return [`String(${text}).length()`, Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['text_isEmpty'] = function (block, generator) {
  const text = generator.valueToCode(block, 'VALUE', Order.NONE) || '""';
  return [`String(${text}).length() == 0`, Order.EQUALITY] as [string, Order];
};

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD BLOCKLY — MATH
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['math_number'] = function (block) {
  const num = parseFloat(block.getFieldValue('NUM') as string);
  return [String(isNaN(num) ? 0 : num), Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['math_arithmetic'] = function (block, generator) {
  const OPS: Record<string, [string, Order]> = {
    ADD: ['+', Order.ADD],
    MINUS: ['-', Order.ADD],
    MULTIPLY: ['*', Order.MULTIPLY],
    DIVIDE: ['/', Order.MULTIPLY],
    POWER: ['', Order.NONE], // handled separately
  };
  const op = block.getFieldValue('OP') as string;
  if (op === 'POWER') {
    const base = generator.valueToCode(block, 'A', Order.NONE) || '0';
    const exp = generator.valueToCode(block, 'B', Order.NONE) || '0';
    return [`pow(${base}, ${exp})`, Order.ATOMIC] as [string, Order];
  }
  const entry = OPS[op];
  // Guard: unknown op (should never happen with valid Blockly blocks)
  if (!entry) return ['0', Order.ATOMIC] as [string, Order];
  const [symbol, order] = entry;
  const lhs = generator.valueToCode(block, 'A', order) || '0';
  const rhs = generator.valueToCode(block, 'B', order) || '0';
  return [`${lhs} ${symbol} ${rhs}`, order] as [string, Order];
};

arduinoGenerator.forBlock['math_constrain'] = function (block, generator) {
  const val = generator.valueToCode(block, 'VALUE', Order.NONE) || '0';
  const low = generator.valueToCode(block, 'LOW', Order.NONE) || '0';
  const high = generator.valueToCode(block, 'HIGH', Order.NONE) || '255';
  return [`constrain(${val}, ${low}, ${high})`, Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['math_random_int'] = function (block, generator) {
  const from = generator.valueToCode(block, 'FROM', Order.NONE) || '0';
  const to = generator.valueToCode(block, 'TO', Order.NONE) || '100';
  // Arduino random(min, max) is exclusive of max, so add 1
  return [`random(${from}, ${to} + 1)`, Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['math_modulo'] = function (block, generator) {
  const lhs = generator.valueToCode(block, 'DIVIDEND', Order.MULTIPLY) || '0';
  const rhs = generator.valueToCode(block, 'DIVISOR', Order.MULTIPLY) || '1';
  return [`${lhs} % ${rhs}`, Order.MULTIPLY] as [string, Order];
};

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD BLOCKLY — VARIABLES
// All variables are declared as `int` for beginner-friendliness on Arduino.
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['variables_get'] = function (block, generator) {
  const name = generator.getVariableName(block.getFieldValue('VAR'));

  // Ensure variable is declared globally even if only 'get' is used
  const currentDef = (generator as any).definitions_[`var_${name}`];
  if (!currentDef) {
    (generator as any).definitions_[`var_${name}`] = `int ${name} = 0;`;
  }

  return [name, Order.ATOMIC] as [string, Order];
};

arduinoGenerator.forBlock['variables_set'] = function (block, generator) {
  const name = generator.getVariableName(block.getFieldValue('VAR'));
  const valueBlock = block.getInputTargetBlock('VALUE');
  const value = generator.valueToCode(block, 'VALUE', Order.ASSIGNMENT) || '0';

  // Smart type detection for variables
  let type = 'int';
  if (valueBlock) {
    if (['text', 'text_join', 'text_append'].includes(valueBlock.type)) {
      type = 'String';
    } else if (valueBlock.type === 'math_number') {
      const numVal = String(valueBlock.getFieldValue('NUM') || '0');
      if (numVal.includes('.')) {
        type = 'float';
      }
    }
  }

  // If already declared, keep/upgrade it
  const currentDef = (generator as any).definitions_[`var_${name}`];
  if (currentDef) {
    if (currentDef.startsWith('String') || type === 'String') {
      type = 'String';
    } else if (currentDef.startsWith('float') || type === 'float') {
      type = 'float';
    }
  }

  const defaultValue = type === 'String' ? '""' : type === 'float' ? '0.0' : '0';
  (generator as any).definitions_[`var_${name}`] = `${type} ${name} = ${defaultValue};`;

  return `${name} = ${value};\n`;
};

arduinoGenerator.forBlock['math_change'] = function (block, generator) {
  const name = generator.getVariableName(block.getFieldValue('VAR'));
  const delta = generator.valueToCode(block, 'DELTA', Order.ADD) || '1';

  // Ensure variable is declared globally even if 'set' was never used
  const currentDef = (generator as any).definitions_[`var_${name}`];
  if (!currentDef) {
    (generator as any).definitions_[`var_${name}`] = `int ${name} = 0;`;
  }

  return `${name} += ${delta};\n`;
};

// ─────────────────────────────────────────────────────────────────────────────
// STANDARD BLOCKLY — PROCEDURES (functions)
// ─────────────────────────────────────────────────────────────────────────────

arduinoGenerator.forBlock['procedures_defnoreturn'] = function (block, generator) {
  const name = generator.getProcedureName(block.getFieldValue('NAME'));
  const branch = generator.statementToCode(block, 'STACK');
  const args =
    (block as any).arguments_
      ?.map((a: string) => `int ${generator.getVariableName(a)}`)
      .join(', ') ?? '';

  const fn = `void ${name}(${args}) {\n${branch}}\n`;
  // Store as a definition so it appears before setup/loop
  (generator as any).definitions_[`proc_${name}`] = fn;
  return '';
};

arduinoGenerator.forBlock['procedures_defreturn'] = function (block, generator) {
  const name = generator.getProcedureName(block.getFieldValue('NAME'));
  const branch = generator.statementToCode(block, 'STACK');
  const retVal = generator.valueToCode(block, 'RETURN', Order.NONE) || '0';
  const args =
    (block as any).arguments_
      ?.map((a: string) => `int ${generator.getVariableName(a)}`)
      .join(', ') ?? '';

  const fn = `int ${name}(${args}) {\n${branch}${generator.INDENT}return ${retVal};\n}\n`;
  (generator as any).definitions_[`proc_${name}`] = fn;
  return '';
};

arduinoGenerator.forBlock['procedures_callnoreturn'] = function (block, generator) {
  const name = generator.getProcedureName(block.getFieldValue('NAME'));
  const args = (((block as any).arguments_ as string[]) ?? [])
    .map((_: string, i: number) => generator.valueToCode(block, `ARG${i}`, Order.NONE) || '0')
    .join(', ');
  return `${name}(${args});\n`;
};

arduinoGenerator.forBlock['procedures_callreturn'] = function (block, generator) {
  const name = generator.getProcedureName(block.getFieldValue('NAME'));
  const args = (((block as any).arguments_ as string[]) ?? [])
    .map((_: string, i: number) => generator.valueToCode(block, `ARG${i}`, Order.NONE) || '0')
    .join(', ');
  return [`${name}(${args})`, Order.ATOMIC] as [string, Order];
};

/**
 * Generates Arduino C++ from a Blockly workspace.
 * Always prefixes the sketch with the correct header and variable declarations.
 */
export function workspaceToArduinoCode(workspace: Workspace): string {
  return arduinoGenerator.workspaceToCode(workspace);
}
