/**
 * editor.store.ts
 *
 * Zustand store for all editor state. Keeps Editor.tsx clean — the page
 * component only reads state and dispatches actions; no async logic lives
 * in the component itself.
 */
import { create } from 'zustand';
import { api } from '../services/api';

// Inline types mirroring apps/api/src/lib/compiler.ts — kept here to avoid
// a cross-package import that can confuse TS server on first open.
export interface CompileError {
  line:     number;
  column:   number;
  message:  string;
  severity: 'error' | 'warning';
}

export interface CompileResult {
  success:    boolean;
  stdout:     string;
  stderr:     string;
  errors:     CompileError[];
  durationMs: number;
}

export type EditorMode = 'block' | 'code';

export interface EditorState {
  // ── Mode ──────────────────────────────────────────────────────────────────
  mode:            EditorMode;
  setMode:         (mode: EditorMode) => void;

  // ── Code ──────────────────────────────────────────────────────────────────
  /** C++ code generated by the Blockly canvas. */
  generatedCode:   string;
  /** Code typed or pasted directly in Monaco. */
  manualCode:      string;
  setGeneratedCode: (code: string) => void;
  setManualCode:    (code: string) => void;

  // ── Board ─────────────────────────────────────────────────────────────────
  board:     string;
  setBoard:  (board: string) => void;

  // ── Compile ───────────────────────────────────────────────────────────────
  isCompiling:   boolean;
  compileResult: CompileResult | null;
  compile:       (code: string) => Promise<void>;
  clearResult:   () => void;

  // ── Project (current open project) ───────────────────────────────────────
  projectId:    string | null;
  projectTitle: string;
  isSaving:     boolean;
  setProjectTitle: (title: string) => void;
  saveProject:     (blockXml: string) => Promise<void>;
}

export const useEditorStore = create<EditorState>()((set, get) => ({
  // ── Mode ──────────────────────────────────────────────────────────────────
  mode: 'block',
  setMode: (mode) => set({ mode }),

  // ── Code ──────────────────────────────────────────────────────────────────
  generatedCode:    '',
  manualCode:       '',
  setGeneratedCode: (generatedCode) => set({ generatedCode }),
  setManualCode:    (manualCode)    => set({ manualCode }),

  // ── Board ─────────────────────────────────────────────────────────────────
  board:    'arduino:avr:uno',
  setBoard: (board) => set({ board }),

  // ── Compile ───────────────────────────────────────────────────────────────
  isCompiling:   false,
  compileResult: null,

  compile: async (code: string) => {
    set({ isCompiling: true, compileResult: null });
    try {
      const { data } = await api.post('/compile', { code, board: get().board });
      set({ compileResult: data.data.result as CompileResult });
    } catch (err: any) {
      // Surface structured API errors as a failed compile result
      const message = err?.response?.data?.error?.message ?? 'Compilation failed unexpectedly';
      set({
        compileResult: {
          success:    false,
          stdout:     '',
          stderr:     message,
          errors:     [{ line: 0, column: 0, severity: 'error', message }],
          durationMs: 0,
        },
      });
    } finally {
      set({ isCompiling: false });
    }
  },

  clearResult: () => set({ compileResult: null }),

  // ── Project ───────────────────────────────────────────────────────────────
  projectId:    null,
  projectTitle: 'New_Project',
  isSaving:     false,

  setProjectTitle: (projectTitle) => set({ projectTitle }),

  saveProject: async (blockXml: string) => {
    const { projectId, projectTitle, generatedCode, board, mode, manualCode } = get();
    set({ isSaving: true });
    try {
      const code = mode === 'code' ? manualCode : generatedCode;
      if (projectId) {
        // Update existing project
        await api.patch(`/projects/${projectId}`, {
          title:      projectTitle,
          code,
          blockState: blockXml,
          boardTarget: board,
        });
      } else {
        // Create a new project and store its ID for subsequent saves
        const { data } = await api.post('/projects', {
          title:      projectTitle,
          type:       mode === 'block' ? 'BLOCK' : 'CODE',
          code,
          blockState: blockXml,
          boardTarget: board,
        });
        set({ projectId: data.data.project.id });
      }
    } finally {
      set({ isSaving: false });
    }
  },
}));
